run:
  timeout: "10m"
linters:
  enable-all: true
  disable:
  - depguard
  - exhaustruct
  - funlen
  - godox
  - musttag
  - nlreturn
  - paralleltest
  - testpackage
  # Deprecated
  - deadcode
  - exhaustivestruct
  - golint
  - ifshort
  - interfacer
  - maligned
  - nosnakecase
  - scopelint
  - structcheck
  - varcheck
linters-settings:
  varnamelen:
    ignore-names:
      - vm
      - wg
      - ig
  lll:
    tab-width: 2
    line-length: 200
  tagliatelle:
    case: 
      rules:
        json: snake
  cyclop:
    max-complexity: 15
