name: generate

on:
  push:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  licenses:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: make cmd/fleeting-plugin-proxmox/licenses.txt
      - shell: bash
        run: |
          git diff
      - shell: bash
        run: |
          [[ -z "$(git status -s)" ]]
