name: test

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: go test -v ./cmd/...
